### PR TITLE
Moved to vue-cli, updated dependencies and prettier config

### PR DESCRIPTION
**Pull request by kmalakoff**
Hey Adam,

I generated a new project with vue-cli and copied the source files in. It seems to be working for the most part, but it would be great to get your opinion before I move much more forward on this.

### CODE REVIEW

**Comment by rikur** [comment]
👍 LGTM. One question @kmalakoff:
How many code quality rules left from eslint aside from "console.log" etc?

I love the formatting of prettier, but I still keep eslint around to enforce good code quality.

https://prettier.io/docs/en/comparison.html

**Comment by kmalakoff** [comment]
@rikur prettier plays well with eslint. On my vue projects, I have also added a more opinionated style (specifically airbnb) in my eslintrc.js file:

```
  extends: ['plugin:vue/essential', '@vue/airbnb', '@vue/prettier'],
```

What I agreed with @asoltys was rather than trying to upgrade webpack from 3 to 4, to move over to vue-cli and prettier as the base which is what this PR is a step towards (but it needs to be tested more exhaustively and updated for the cordova build process). 

After we agreed for me to do this, Adam updated coinos-server to use prettier: https://github.com/asoltys/coinos-server/commit/cb30426a5053345396b6ec1705fbf239df16f4c3

I'm not sure what the CoinOS community prefers so what I would recommend is to choose the eslint configuration base (eg. airbnb, standard, google, etc) in addition to prettier for both CoinOS repos and then configure both projects to be consistent.

**Comment by asoltys** [comment]
This is great, thanks Kevin!

**Comment by rikur** [comment]
@kmalakoff ah I missed that line of new extends. All good, I prefer opinionated formatting in OSS projects.

**Pull request merged**
